### ISSUE TITLE
換人問題

### ISSUE THREAD

**Issue by notherben** [Zhen-Bo/Fgo-JP#3]
不好意思請問一下https://github.com/Zhen-Bo/Fgo-Script在這個腳本中，換人的指令該如何使用啊？
我試了好久都無法使用 拜託教我一夏 謝謝大大

**Comment by Zhen-Bo** [comment]
換人技能則為"x",而非 m 開頭,x 後接需要更換的前牌從者站位 1~3,和後牌從者站位 1~3(對應:4~6)

請仔細看完README後在發問....

**Comment by notherben** [comment]
請問是輸入 x14 這樣嗎? 還是該怎麼輸入 抱歉 我真的看不懂這句話的意思

**Comment by Zhen-Bo** [comment]
1~3....

notherben ***@***.***> 於 2021年8月31日 週二 下午5:57寫道：

**Comment by notherben** [comment]
我不管怎麼試 都無法成功欸 它都會在打開換人頁面之後 就直接結束程式 像是這樣
![123](https://user-images.githubusercontent.com/89840331/131485969-e9303feb-69e3-4bd5-844e-96c3533d3c2b.png)

**Comment by Zhen-Bo** [comment]
你把31換成20看會不會正常,第一個角色對應0 第二個對應1

notherben ***@***.***> 於 2021年8月31日 週二 下午6:20寫道：

**Comment by Zhen-Bo** [comment]
補充下,請有一定python能力再使用這個腳本,因為我並沒有打算把這個當做一個自己的github專案練習
如果有程式部分我很歡迎討論,至於使用問題部分,請自行看source code會比較快,沒有人會記得自己7個月前搞了什麼東西,而且github上也有其他版本

**Comment by notherben** [comment]
> 補充下,請有一定python能力再使用這個腳本,因為我並沒有打算把這個當做一個自己的github專案練習
> 如果有程式部分我很歡迎討論,至於使用問題部分,請自行看source code會比較快,沒有人會記得自己7個月前搞了什麼東西,而且github上也有其他版本

好吧 謝謝你願意抽空回答我的問題 我再自己找找有沒有其他的腳本好了 感謝你
